[build]
    command = "yarn build --environment=staging"

[context.master]
    command = "yarn build --environment=production"

[context.branch-deploy]
    command = "yarn build --environment=development"

# enable entry to app through routes other than /
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
